sonar.projectKey=lucizzs_Project_Architectura
sonar.organization=lucizzs
sonar.projectVersion=2.0.0

# Source & tests
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/junit.xml
# Quality Gate thresholds
sonar.coverage.exclusions=**/node_modules/**,**/dist/**

# Encoding
sonar.sourceEncoding=UTF-8
